### PR TITLE
Updated BOM with Mouser part numbers, prices and link to Mouser Project

### PR DESCRIPTION
**Pull request by timgiles**
As above, added as many Mouser parts as I could find and a link to the Project.

### CODE REVIEW

**Comment by kolesar007** [comment]
timgiles I go trough your BOM list and found some mistakes in it.
1. SRF0703-821M must be 2 and not 4 pcs
2. 39-01-4050 only one is needed
3. CT2234-0 must be 2 pcs
4. 2-2178710-0 is for ribon cabel

**Comment by timgiles** [comment]
Thanks Kolesar. I have corrected in the Mouser Project listing, the first 3 mistakes. The forth item, I have corrected. It should be a 40 pin connector. I found the same as farnell have. Thank you very much for looking through it - always better to have more than 1 pair of eyes for reviewing large BoMs!

I will resubmit to Prasimix shortly. Next 48hrs.

**Comment by timgiles** [comment]
Prasimix, expect an updated BoM in the next day or two. I have updated the sheet and the Mouser Project, just dont have time to upload the ODS file to you this minute.

**Comment by prasimix** [comment]
Strange how you ends up with 2-2178710-0 since Farnell part [7992033](http://export.farnell.com/harwin/m20-7832046/socket-pcb-0-1-20-20way/dp/7992033?ost=7992033&selectedCategoryId=&categoryNameResp=All%2BCategories&searchView=table&iscrfnonsku=false) looks fine to me.

**Comment by prasimix** [comment]
I got from another member the following list of issues found in current Mouser section:

| Position | Part No. | Comment |
| --- | --- | --- |
| **1** | 571-5-146254-3 | This is male pin header. Does not suit to the project. |
| **11** | 581-08051U150FAT2A | We don't need 18p 1% 100V RF capacitor there |
| **24** | 594-2222-367-56473 | Please check if this is ok to use |
| **34** | 667-EEE-TG1J101UP | This has worse parameters and is more expensive than FK-series |
| **38** | 511-BAT54SFILMY | This replacement is 3x more expensive than usual BAT54S |
| **81** | 571-2-2178710-0 | This replacement is not suitable for LCD connector. |
| **110** | 66-W2222R0JRLF | This is axial resistor. Basically it's ok, but needs insulator tubing on one end |
| **124** | 279-3520330RJT | This has rated power 1W only. |
| **127** | 791-WR08X1003FTL | Wrong nominal. |
| **136** | 756-LRMAM2512R02FT4 | This has rated power 1W only. |
| **139** | 490-CST-951AP | Voltage rating is 5V. Probably ok ? |
| **145** | 710-61400413321 | Please check datasheet. Pins shifted 0,2mm. Is it ok? |
| **152** | 710-610126249221 | This is SMD connector. Does not suit to the project. |
| **156** | 710-615008138321 | Please check datasheet. LEDs are wrong way and there is no info about transformer |

**Pull request merged**
